# Generated by Django 5.2 on 2025-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
