# Generated by Django 5.2 on 2025-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('expired', 'منقضی شده')], default='pending', max_length=10),
        ),
    ]
